sonar.projectKey=menuiseriembb01-boop_stock-quality-project
sonar.organization=menuiseriembb01-boop
sonar.projectName=Stock Quality - Séga Diallo
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.qualitygate.wait=true